# Generated by Django 5.1.5 on 2025-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_funcionario_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("titulo", models.CharField(max_length=30, verbose_name="Título")),
                (
                    "descricao",
                    models.TextField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("lni-rocket", "Foguete"),
                            ("lni-laptop-phone", "Laptop"),
                            ("lni-cog", "Engrenagem"),
                            ("lni-leaf", "Folha"),
                            ("lni-layers", "Camadas"),
                        ],
                        max_length=16,
                        verbose_name="Ícone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
    ]
