# Generated by Django 5.1.4 on 2024-12-27 23:50

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço"
                    ),
                ),
                ("estoque", models.IntegerField(verbose_name="Estoque")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="produtos",
                        variations={
                            "thumb": {"crop": True, "height": 124, "width": 124}
                        },
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
