services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: fusion
      POSTGRES_PASSWORD: fusion
      POSTGRES_DB: fusion
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb/:/initdb/docker-entrypoint-initdb.d
volumes:
  db: